function worldCups() {
  const data = {
    1930: {
      hostCountry: 'Uruguay',
      winner: 'Uruguay',
      runnerUp: 'Argentina',
      topGoalScorer: [{ name: 'Guillermo Stábile', country: 'Argentina', numberOfGoals: 8 }],
      totalAttendance: 590549,
      numberOfMatches: 18,
    },
    1934: {
      hostCountry: 'Italy',
      winner: 'Italy',
      runnerUp: 'Czechoslovakia',
      topGoalScorer: [{ name: 'Oldřich Nejedlý', country: 'Czechoslovakia', numberOfGoals: 5 }],
      totalAttendance: 363000,
      numberOfMatches: 17,
    },
    1938: {
      hostCountry: 'France',
      winner: 'Italy',
      runnerUp: 'Hungary',
      topGoalScorer: [{ name: 'Leônidas', country: 'Brazil', numberOfGoals: 7 }],
      totalAttendance: 375000,
      numberOfMatches: 18,
    },
    1950: {
      hostCountry: 'Brazil',
      winner: 'Uruguay',
      runnerUp: 'Brazil',
      topGoalScorer: [{ name: 'Ademir', country: 'Brazil', numberOfGoals: 8 }],
      totalAttendance: 1045246,
      numberOfMatches: 22,
    },
    1954: {
      hostCountry: 'Switzerland',
      winner: 'West Germany',
      runnerUp: 'Hungary',
      topGoalScorer: [{ name: 'Sándor Kocsis', country: 'Hungary', numberOfGoals: 11 }],
      totalAttendance: 768607,
      numberOfMatches: 26,
    },
    1958: {
      hostCountry: 'Sweden',
      winner: 'Brazil',
      runnerUp: 'Sweden',
      topGoalScorer: [{ name: 'Just Fontaine', country: 'France', numberOfGoals: 13 }],
      totalAttendance: 819810,
      numberOfMatches: 35,
    },
    1962: {
      hostCountry: 'Chile',
      winner: 'Brazil',
      runnerUp: 'Czechoslovakia',
      topGoalScorer: [
        { name: 'Garrincha', country: 'Brazil', numberOfGoals: 4 },
        { name: 'Vavá', country: 'Brazil', numberOfGoals: 4 },
        { name: 'Leonel Sánchez', country: 'Chile', numberOfGoals: 4 },
        { name: 'Flórián Albert', country: 'Hungary', numberOfGoals: 4 },
        { name: 'Valentin Ivanov', country: 'Soviet Union', numberOfGoals: 4 },
        { name: 'Dražan Jerković', country: 'Yugoslavia', numberOfGoals: 4 },
      ],
      totalAttendance: 893172,
      numberOfMatches: 32,
    },
    1966: {
      hostCountry: 'England',
      winner: 'England',
      runnerUp: 'West Germany',
      topGoalScorer: [{ name: 'Eusébio', country: 'Portugal', numberOfGoals: 9 }],
      totalAttendance: 1563135,
      numberOfMatches: 32,
    },
    1970: {
      hostCountry: 'Mexico',
      winner: 'Brazil',
      runnerUp: 'Italy',
      topGoalScorer: [{ name: 'Gerd Müller', country: 'West Germany', numberOfGoals: 10 }],
      totalAttendance: 1603975,
      numberOfMatches: 32,
    },
    1974: {
      hostCountry: 'West Germany',
      winner: 'West Germany',
      runnerUp: 'Netherlands',
      topGoalScorer: [{ name: 'Grzegorz Lato', country: 'Poland', numberOfGoals: 7 }],
      totalAttendance: 1865753,
      numberOfMatches: 38,
    },
    1978: {
      hostCountry: 'Argentina',
      winner: 'Argentina',
      runnerUp: 'Netherlands',
      topGoalScorer: [{ name: 'Mario Kempes', country: 'Argentina', numberOfGoals: 6 }],
      totalAttendance: 1545791,
      numberOfMatches: 38,
    },
    1982: {
      hostCountry: 'Spain',
      winner: 'Italy',
      runnerUp: 'West Germany',
      topGoalScorer: [{ name: 'Paolo Rossi', country: 'Italy', numberOfGoals: 6 }],
      totalAttendance: 2109723,
      numberOfMatches: 52,
    },
    1986: {
      hostCountry: 'Mexico',
      winner: 'Argentina',
      runnerUp: 'West Germany',
      topGoalScorer: [{ name: 'Gary Lineker', country: 'England', numberOfGoals: 6 }],
      totalAttendance: 239403,
      numberOfMatches: 52,
    },
    1990: {
      hostCountry: 'Italy',
      winner: 'West Germany',
      runnerUp: 'Argentina',
      topGoalScorer: [{ name: 'Salvatore Schillaci', country: 'Italy', numberOfGoals: 6 }],
      totalAttendance: 2516215,
      numberOfMatches: 52,
    },
    1994: {
      hostCountry: 'United States',
      winner: 'Brazil',
      runnerUp: 'Italy',
      topGoalScorer: [{ name: 'Oleg Salenko', country: 'Russia', numberOfGoals: 6 }, { name: 'Hristo Stoichkov', country: 'Bulgaria', numberOfGoals: 6 }],
      totalAttendance: 3587538,
      numberOfMatches: 52,
    },
    1998: {
      hostCountry: 'France',
      winner: 'France',
      runnerUp: 'Brazil',
      topGoalScorer: [{ name: 'Davor Šuker', country: 'Italy', numberOfGoals: 6 }],
      totalAttendance: 2785100,
      numberOfMatches: 64,
    },
    2002: {
      hostCountry: 'South Korea,Japan',
      winner: 'Brazil',
      runnerUp: 'Germany',
      topGoalScorer: [{ name: 'Ronaldo', country: 'Brazil', numberOfGoals: 8 }],
      totalAttendance: 2705197,
      numberOfMatches: 64,
    },
    2006: {
      hostCountry: 'Germany',
      winner: 'Italy',
      runnerUp: 'France',
      topGoalScorer: [{ name: 'Miroslav Klose', country: 'Germany', numberOfGoals: 5 }],
      totalAttendance: 3359439,
      numberOfMatches: 64,
    },
    2010: {
      hostCountry: 'South Africa',
      winner: 'Spain',
      runnerUp: 'Netherlands',
      topGoalScorer: [
        { name: 'Diego Forlán', country: 'Uruguay', numberOfGoals: 5 },
        { name: 'Thomas Müller', country: 'Germany', numberOfGoals: 5 },
        { name: 'Wesley Sneijder', country: 'Netherlands', numberOfGoals: 5 },
        { name: 'David Villa', country: 'Spain', numberOfGoals: 5 },
      ],
      totalAttendance: 3178856,
      numberOfMatches: 64,
    },
    2014: {
      hostCountry: 'Brazil',
      winner: 'Germany',
      runnerUp: 'Argentina',
      topGoalScorer: [{ name: 'James Rodríguez', country: 'Colombia', numberOfGoals: 6 }],
      totalAttendance: 3429873,
      numberOfMatches: 64,
    },
    2018: {
      hostCountry: 'Russia',
      winner: 'France',
      runnerUp: 'Croatia',
      topGoalScorer: [{ name: 'Harry Kane', country: 'England', numberOfGoals: 6 }],
      totalAttendance: 3031768,
      numberOfMatches: 64,
    },
    2022: {
      hostCountry: 'Qatar',
      winner: 'Argentina',
      runnerUp: 'France',
      topGoalScorer: [{ name: 'Kylian Mbappe', country: 'France', numberOfGoals: 8 }],
      totalAttendance: 3404252,
      numberOfMatches: 64,
    },
  };

  return {
    year: tournamentYear => data[tournamentYear],
  };
}

module.exports = worldCups();
